logging:
    level:
     root: info

server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 1
        minIdle: 3
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 30000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        # 合并多个DruidDataSource的监控数据
        useGlobalDataSourceStat: true

    rabbitmq:
        host: 8.136.117.38
        port: 5672
        username: admin
        password: admin
        virtual-host: /
        publisher-confirms: true  #如果对异步消息需要回调必须设置为true
        publisher-returns: true
        listener:
            simple:
                concurrency: 1 #最小消费者
                max-concurrency: 20 #最大消费者
                acknowledge-mode: manual # 消费手动确认
            direct:
                retry:
                    enabled: true # 开启消费者进行重试
                    max-attempts: 5 #最大重试次数
                    initial-interval: 60 # 重试时间间隔 S
    redis:
        host: 8.136.117.38
        port: 6379
        connect-timeout: 1000
        # 连接池配置
        lettuce:
            shutdown-timeout: 2000
            pool:
                max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
                max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-idle: 10    # 连接池中的最大空闲连接
                min-idle: 2     # 连接池中的最小空闲连接
            # 集群配置
                #cluster:
                    #refresh:
                # dynamic-refresh-sources: false
        timeout: 2000  # 连接超时时间（毫秒）
        password: lsp@123456

mybatis-plus:
    # MyBatis Mapper所对应的XML文件位置
    mapper-locations: classpath*:/mapper/*Mapper.xml
    global-config:
        # 关闭MP3.0自带的banner
        banner: false
        db-config:
            # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
            id-type: AUTO
            #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
            insert-strategy: NOT_NULL
            update-strategy: NOT_NULL
            select-strategy: NOT_NULL
            # 默认数据库表下划线命名
            table-underline: true
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#jwt
jwt:
    header: Authorization
    # 令牌前缀
    token-start-with: Bearer
    # 使用Base64对该令牌进行编码
    base64-secret: N2ZlZTU1YTJhNDdmZTE5ODJhZGZjN2U4NTAzNGVhNTM5OGU1YmM0ZjkwZDI3MzNmN2YxMDI0ZTA1MzM5YzgzNDUyNzIwNjA2ZGY3OTJkMTg2Mjk1MmE1YTBiNTAxN2RhZWJhZDI0NmJlMDNhNDU4M2JjOTg4ZjkzNTczOWZlMDg
    # 令牌过期时间 此处单位/毫秒
    token-validity-in-seconds: 14400000